<?xml version="1.0"?>
<robot name="accurate_noah"
	xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find noah_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/wheel.urdf.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/camera_sensor.urdf.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/accurate_base_link.urdf.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/caster_link.urdf.xacro" />


	<xacro:property name="M_PI" value="3.14159"/>

	<!-- Whole accurate_base_link dimensions -->
	<xacro:property name="base_width" value="0.16426" />
	<xacro:property name="base_depth" value="0.19" />
	<xacro:property name="base_height" value="0.056" />

	<xacro:property name="caster_radius" value="0.022" />

	<xacro:property name="wheel_length" value="0.02" />
	<xacro:property name="wheel_radius" value="0.05" />

	<xacro:property name="camera_size" value="0.02" />


	<!-- Base Link -->
	<xacro:accurate_base_link />

	<!-- Caster -->
	<xacro:caster caster_radius="${caster_radius}" parent_link="caster_holder_link">
		<origin xyz="0 0 0" rpy="0 0 0" />
	</xacro:caster>


	<!-- Wheels -->
	<xacro:noah_wheel wheel_prefix="left" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}" parent_link="left_wheel_adapter_link">
		<origin xyz="0 ${wheel_length/2} 0" rpy="0 0 0" />
	</xacro:noah_wheel>

	<xacro:noah_wheel wheel_prefix="right" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}" parent_link="right_wheel_adapter_link">
		<origin xyz="0 -${wheel_length/2} 0" rpy="0 0 0" />
	</xacro:noah_wheel>

	<!-- Camera -->
	<xacro:noah_camera camera_size="${camera_size}" parent_link="top_generic_link">
		<!-- 0.0015 is half the heigth of top generic link -->
		<origin xyz="${base_depth/3} 0 ${camera_size/2 + 0.0015}" rpy="0 0 0" />
	</xacro:noah_camera>

	<!-- *******Gazebo specific******* -->

	<gazebo>
    <!-- For ros2 we use gazebo_ros_joint_state_publisher instead of publishWheelJointState -->
    <plugin name="joint_states" filename="libgazebo_ros_joint_state_publisher.so">
      <joint_name>right_wheel_joint</joint_name>
      <joint_name>left_wheel_joint</joint_name>
    </plugin>

		<plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

      <ros>
        <namespace>/noah</namespace>
        <!-- For the topics being published we would remap doing: -->
        <!-- <argument>cmd_vel:=cmd_demo</argument> -->
        <!-- <argument>odom:=odom_demo</argument> -->
      </ros>

      <!-- wheels -->
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>1.25</wheel_separation>
      <wheel_diameter>0.3</wheel_diameter>

      <!-- limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <!-- output -->
			<update_rate>20</update_rate>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_generic_link</robot_base_frame>

			<command_topic>cmd_vel</command_topic>
      <publish_wheel_tf>true</publish_wheel_tf>
			<torque>20</torque>

		</plugin>
	</gazebo>

</robot>
