<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="noah_camera">

  <xacro:macro name="noah_camera" params="camera_size parent_link *joint_pose">

    <xacro:property name="lens_size" value="0.01"/>

    <!-- Link describing the camera "box" -->
    <link name="camera_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_size} ${camera_size} ${camera_size}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_size} ${camera_size} ${camera_size}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <!-- Where the camera attaches to parent_link, given by param -->
    <joint name="camera_joint" type="fixed">
      <xacro:insert_block name="joint_pose"/>
      <parent link="${parent_link}" />
      <child link="camera_link" />
    </joint>

    <!-- Link and joint to position correctly the camera lens, where the sensor rays start -->
    <link name="lens_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.0001 ${lens_size} ${lens_size}" />
        </geometry>
        <material name="white"/>
      </visual>
    </link>
    <joint name="lens_camera_joint" type="fixed">
      <origin xyz="${camera_size/2} 0 0" rpy="0 0 0" />
      <parent link="camera_link" />
      <child link="lens_link"/>
    </joint>


    <!-- This next two link and joints are taken from the husky robot. They are meant to correct the kinect point cloud camera position.-->
    <!-- this link is the origin for the camera's data -->
    <link name="kinect" />
    <joint name="kinect_lens_joint" type="fixed">
      <parent link="lens_link"/>
      <child link="kinect"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!--
      The gazebo plugin aligns the depth data with the Z axis, with X=left and Y=up
      ROS expects the depth data along the X axis, with Y=left and Z=up
      This link only exists to give the gazebo plugin the correctly-oriented frame -->

    <link name="kinect_gazebo" />
    <joint name="kinect_gazebo_joint" type="fixed">
      <parent link="kinect"/>
      <child link="kinect_gazebo"/>
      <origin xyz="0.0 0 0" rpy="-1.5707963267948966 0 -1.5707963267948966"/>
    </joint>

  </xacro:macro>

</robot>
