#!/bin/bash
# Runs the provided command in a docker container with Noah simulation code and dependencies.

xhost +local:root
docker run --rm -it \
	--name noah_docker_ros2_run \
	--gpus all \
	-e "TERM=xterm-256color" \
	-e DISPLAY \
	-v /dev/dri:/dev/dri \
	-v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
	noahbot:humble \
	$@
